export const ADD_TODO = 'ADD_TODO'
export const FETCH_TODOS = 'FETCH_TODOS'
export const FETCH_TODO = 'FETCH_TODO'
export const MARK_COMPLETED = 'MARK_COMPLETED'
export const EDIT_TODO = 'EDIT_TODO'
export const DELETE_TODO = 'DELETE_TODO'
